build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    comments: 1

processors:
  active: false

console-reports:
  active: true

output-reports:
  active: true
  exclude:
      - 'HtmlOutputReport'
      - 'TxtOutputReport'

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: false
  EqualsWithHashCodeExist:
    active: true
  WrongEqualsTypeParameter:
    active: false
  IteratorHasNextCallsNextMethod:
    active: false
  ExplicitGarbageCollectionCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: false
  IteratorNotThrowingNoSuchElementException:
    active: false
  UnreachableCode:
    active: true
  LateinitUsage:
    active: false
    ignoreAnnotated: []
    ignoreOnClassesPattern: ''
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: false
  UselessPostfixExpression:
    active: false

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: false
  UnnecessaryTemporaryInstantiation:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
    methodNames: ['toString', 'hashCode', 'equals', 'finalize']
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    exceptionNames:
     - ArrayIndexOutOfBoundsException
     - Error
     - Exception
     - IllegalMonitorStateException
     - IndexOutOfBoundsException
     - InterruptedException
     - NullPointerException
     - RuntimeException
     - Throwable
    allowedExceptionNameRegex: 'e|_|(ignore|expected).*'
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
     - Error
     - Exception
     - NullPointerException
     - RuntimeException
     - Throwable
  InstanceOfCheckForException:
    active: false
  NotImplementedDeclaration:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    exceptions: ['IllegalArgumentException', 'IllegalStateException', 'IOException']
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: false
  ThrowingNewInstanceOfSameException:
    active: false

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: false
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

complexity:
  active: true
  LongMethod:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    threshold: 60
  NestedBlockDepth:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    threshold: 4 # TODO: create custom rule that doesn't count run/let/apply/etc.
  LongParameterList:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt', '**/*Builder.kt', '**/*Module.kt', '**/designdemo/**/*Entity.kt' ]
    functionThreshold: 6
    constructorThreshold: 100
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotated: [ 'Inject', 'Composable' ]
  LargeClass:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    threshold: 600
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: false
  ComplexMethod:
    active: false
    threshold: 10
  MethodOverloading:
    active: false
    threshold: 5
  TooManyFunctions:
    active: false
    thresholdInFiles: 10
    thresholdInClasses: 10
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 10
  ComplexCondition:
    active: true
    threshold: 5
  LabeledExpression:
    active: false
  StringLiteralDuplication:
    active: false
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'

naming:
  active: true
  MemberNameEqualsClassName:
    active: false
    ignoreOverridden: true
  ClassNaming:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    classPattern: '[A-Z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
    ignoreOverridden: true
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'
  PackageNaming:
    active: false
  FunctionNaming:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    functionPattern: '([a-z][a-zA-Z0-9]*)|(`.*`)'
    ignoreAnnotated: ['Composable']
  FunctionParameterNaming:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    parameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
    ignoreOverridden: true
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: false
    minimumFunctionNameLength: 3
  VariableNaming:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  TopLevelPropertyNaming:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 30
  VariableMinLength:
    active: false
    minimumVariableNameLength: 3
  ForbiddenClassName:
    active: false
    forbiddenName: []

style:
  active: true
  ReturnCount:
    active: true
    max: 3
  ThrowsCount:
    active: true
    max: 2
  NewLineAtEndOfFile:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalWhenBraces:
    active: false
  CollapsibleIfStatements:
    active: false
  EqualsNullCall:
    active: false
  EqualsOnSignatureLine:
    active: true
  ForbiddenComment:
    active: true
    values: ['STOPSHIP']
  ForbiddenImport:
    active: true
    imports: ['kotlinx.android.parcel.Parcelize']
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 1
  ModifierOrder:
    active: true
  MagicNumber:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt', '**/designdemo/**/*Entity.kt' ]
    ignoreNumbers: ['-1','0','1','2']
    ignoreHashCodeFunction: false
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
  WildcardImport:
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    active: true
  SafeCast:
    active: true
  MaxLineLength:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt' ]
    maxLineLength: 160
    excludePackageStatements: false
    excludeImportStatements: false
  ProtectedMemberInFinalClass:
    active: false
  SerialVersionUIDInSerializableClass:
    active: false
  UnnecessaryParentheses:
    active: false
  UnnecessaryInheritance:
    active: false
  UtilityClassWithPublicConstructor:
    active: false
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix: 'to'
  UseDataClass:
    active: false
  UnnecessaryAbstractClass:
    active: false
  OptionalUnit:
    active: true
  ExpressionBodySyntax:
    active: true
  UnusedImports:
    active: true
  NestedClassesVisibility:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  FunctionOnlyReturningConstant:
    active: true
    ignoreAnnotated: ['Provides']
    ignoreOverridableFunction: true
    excludedFunctions: 'describeContents'
  LibraryCodeMustSpecifyReturnType:
    active: true
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt', '**/*InstrumentationTestUtils/**' ]
  MandatoryBracesIfStatements:
    active: true
  MayBeConst:
    active: true

comments:
  active: true
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    excludes: [ '**/src/test/**', '**/src/androidTest/**', '**/*Test.kt', '**/*.Spec.kt', '**/*InstrumentationTestUtils/**' ]
    active: true
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false
